name: "BuildFFA"
version: "1.0"
author: "xxAROX"
website: "https://github.com/xxAROX/"
description: "BuildFFA plugin by xxAROX."
url: "https://github.com/RyZerBE/BuildFFA"

api: [ "4.0.0" ]
main: xxAROX\BuildFFA\BuildFFA